### ISSUE TITLE
How to Not Use Depin？

### ISSUE THREAD

**Issue by 654955321** [CMB27/ModbusRTUMaster#11]
<img width="360" alt="Snipaste_2024-03-10_21-41-17" src="https://github.com/CMB27/ModbusRTUMaster/assets/9605294/5d4dcac7-0352-40ba-b251-8963a6f1d919">
In my circuit design, there is no DEPIN, and R485 automatically switches between sending and receiving. How to modify and use your library?

**Comment by 654955321** [comment]
I changed it to "NO_DE_PIN", but the problem still exists. The MCU I use is STM32F103, and I use PlatformIO to compile it. The error prompts that the "avr/interrupt.h" header file cannot be found. Can this library be used normally on stm32?
![image](https://github.com/CMB27/ModbusRTUMaster/assets/9605294/a9e6a992-b44b-4258-bb0f-7143d97c9210)

**Comment by CMB27** [comment]
It looks like you are having issues with `SoftwareSerial` not the DE pin.
I have not tested this library with STM32 microcontrollers, so I don't know how or if this library will work on that platform.

If you share your code, I may be able to help a little more, but I can't guarantee it will work.
