### ISSUE TITLE
How to send a coil to all clients?

### ISSUE THREAD

**Issue by saiid2020** [CMB27/ModbusRTUMaster#3]
There is no code for broadcast?

**Comment by CMB27** [comment]
There is a way to send broadcast messages. Use `0` as the `slaveId`. Note this only works with the write functions: `writeSingleCoil`, `writeSingleHoldingRegister`, `writeMultipleCoils`, and `writeMultipleHoldingRegisters`.

e.g.

``` C++
writeSingleCoil(0, 5, true);
```
To set coil 5 `true` on all the slave/server devices connected to the bus.
